<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260829205641 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE quiz_score (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, score INT NOT NULL, rounds INT NOT NULL, clip_length INT NOT NULL, guess_mode VARCHAR(20) NOT NULL, played_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, owner_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_CEEA4ED17E3C61F9 ON quiz_score (owner_id)');
        $this->addSql('ALTER TABLE quiz_score ADD CONSTRAINT FK_CEEA4ED17E3C61F9 FOREIGN KEY (owner_id) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE quiz_score DROP CONSTRAINT FK_CEEA4ED17E3C61F9');
        $this->addSql('DROP TABLE quiz_score');
    }
}
